<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/01/06 16:06:07
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
