<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/01/06 11:58:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
